
# 主题模式配置
theme:
  switch: true  # 如果为 false，则不会出现主题切换按钮，只加载设置的默认主题模式
  default: style-light  # 设置默认主题模式为暗色模式

# Open Graph protocol | OG 协议
open_graph: true # 启用
user:
  name: TDCQCX
  first_name: 个人博客
  last_name: 浮生记
  email: tdcqcx@gmail.com
  domain: blog.tdcqcx.cn
  avatar: /images/site-avatar.jpg
  describe: 这是我的个人博客，记录我的生活和编程之路。
  rule_text: 申请友链需满足：原创内容≥70%、文章≥30篇、HTTPS部署、内容合法合规

favicon:
  logo: /img/favicon.svg # logo | 顶部 logo
  icon16: /img/favicon.svg # icon 16*16
  icon32: /img/favicon.svg # icon 32*32
  apple_touch_icon: # Apple touch icon | iOS 添加到桌面时显示图标
  webmanifest: # Webmanifest | 应用程序清单文件
  visibilitychange: true # Enable toggle title display when leaving | 开启离开时切换标题显示
  hidden: /failure.ico # Displays an icon when not visible | 离开窗口时显示图标
  show_text: favicon.show_text # Displays text when the window is activated | 激活窗口时显示文字
  hide_text: favicon.hide_text # Leave the window to display text | 离开窗口显示文字

top_bars:
  - title: 首页
    url: /
    noswup: true
  - title: 归档
    url: /archives/
    noswup: true
    children:
      - title: 分类
        url: /categories/
      - title: 标签
        url: /tags/
  - title: 关于
    url: /about/
    noswup: true
  - title: 友链
    url: /links/
    noswup: true

sidebar:
  typed_text_prefix: 你好！
  typed_text: ["欢迎来到这！", "我是TDCQCX！", "这里有无限可能！", "好像有什么神奇的事情发生了！", "欢迎来到我的博客！"]
  social: # 社交地址
    - name: Github
      icon: fab fa-github
      url: https://github.com/TDCQCX
      color: "#181717"
      title: Github
      tooltip: Github
      tooltip_position: right
      tooltip_position_mobile: bottom
      tooltip_position_pc: bottom

    - name: 微博
      icon: fab fa-weibo
      url: https://weibo.com/u/7495045812
      color: "#E6162D"
      title: 微博
      tooltip: 微博
      tooltip_position: right
      tooltip_position_mobile: bottom
      tooltip_position_pc: bottom

    - name: Gmail
      icon: fas fa-envelope
      url: mailto:tdcqcx@gmail.com
      color: "#D44638"
      title: Gmail
      tooltip: Gmail
      tooltip_position: right
      tooltip_position_mobile: bottom
      tooltip_position_pc: bottom
      
    
  info: # 个人信息
    - key: 地址
      val: Chengdu China
    - key: 邮箱
      val: tdcqcx@gmail.com
    - key: QQ
      val: 3290264220

  
# About page settings | 关于页
about:
  insert: none #  插入规则  <[before,after,none]>
  title: 如果一切都是镜花水月，那就让这万物走向终结。如果一切皆是命中注定，那就让这世界消失殆尽。 # 标题
  introduction: 大家好，我是 <strong>TDCQCX</strong>，很高兴您能在浩瀚如烟的互联网世界里发现这个博客，更感谢您能够饶有兴致地浏览这个页面。建立这个 Blog 是出于兴趣爱好，我将在此分会分享一些学习笔记，可能还会分享少许图片、视频以及其他有趣东西的链接。 # 个人简单描述
  blog: <ul class="trm-list"><li>程序：TDCQCX </li><li>主题：Hexo-theme-async </li><li>设计：async </li></ul>  # 博客信息
  privacy: 本网站不会追踪访客行为，且不要求访客提供任何敏感信息（比如真实姓名、身份证号码、手机号等），因而也不存在任何隐私泄漏问题。访客参与评论，必须遵守法律法规和基本道德规范，文明礼貌。严禁发布任何有关淫秽、反动、暴力、博彩、恐吓、低俗的内容或违法信息，在尊重言论自由的同时请保持和平与理性。请勿对他人采取不友好的评论或其它过激行为。 # 隐私权说明

#横幅
#每个页面横幅都可以自定义不同背景图、标语等，当您需要视频背景的时候，您的视频格式需要为 MP4、WebM 、Ogg 等格式。
#
#use_cover：文章详情页 banner 是否使用文章封面图，默认 false
#default：默认配置
#type：横幅类型 img、slideshow、video
#bgurl：背景图地址，如果 type 是 slideshow，必须为数组。如果 type 是 img 时，可为字符串或数组，如果数组长度为 2 则会根据主题自动切换。
#banner_title：横幅上标题
#banner_text：横幅描述
#position： 同 CSS object-position
#fit：同 CSS object-fit
#index：首页 (属性字段和上面保持一致)
#video_url：视频地址 (仅首页有)
#archive：分类页 (属性字段和上面保持一致)
#links：友链页 (属性字段和上面保持一致)
#comment：评论页 (属性字段和上面保持一致)
#about：关于 (属性字段和上面保持一致)
banner:
  use_cover: true
  index:
    type: video
    bgurl:
      - img/v4.mp4
    animation: fade  # 切换动画效果
    banner_title: 浮生若梦，<br>为欢几何。
    banner_text: Welcome to here👋,This is 浮生记.
  archive: ## 归档页横幅
    type: img
    bgurl:
      - /images/pages/archive.svg
    banner_title: 云间连下榻，<br>天上接行杯。
    banner_text: The article archive
  comment: ## 评论页横幅
    banner_title: 人生得意须尽欢，<br>莫使金樽空对月。
    banner_text: Leave a message
  links: ## 友链页横幅
    type: img
    bgurl:
      - /images/pages/links.svg
    banner_title: 莫愁前路无知己，<br>天下谁人不识君。
    banner_text: A link to a friend's website
  about: ## 关于页横幅
    type: img
    bgurl:
      - /images/pages/about.svg
    banner_title: 醉后不知天在水，<br>满船清梦压星河。
    banner_text: About me



#    弹幕动画
  #danmu
  #enable：是否开启弹幕动画插件
  #el：弹幕填充区域，默认 banner 元素
  #avatar：是否显示头像，默认 false
  #speed：弹幕每秒滚动距离，默认每秒滚动 20px
  #height：弹幕高度，默认 36px
  #gapWidth：弹幕前后间隔，默认 20px
  #gapHeight：弹幕上下间隔，默认 20px
  #delayRange：延时范围时间，默认 5000 ms
  #align：弹幕对齐方式，参考 align-items
  #mode：弹幕区域大小，'half' | 'top' | 'full'
  danmu:
    enable: false
    avatar: false
    delayRange: 5000
    speed: 80

footer:
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 01/03/2025 17:00:00
  powered:
    enable: false
  beian:
    enable: true
    icp: 蜀ICP备87583212号
  copyright_year: 2025
  custom_text: 你已经看到这了，很累了，休息一下吧。
toc:
    enable: true
    list_number: true
    post_title: true
    max_depth: 3
    min_depth: 1

lazyload:
  enable: true

archive:
  type: more

creative_commons:
  license: by-nc-sa
  language: deed.zh-hans
  post: false
  clipboard: false

post_pagination:
  enable: true
  type: small

notice_outdate:
  enable: true
  style: flat
  limit_day: 365
  position: top

  categorie_card:
    enable: true
    len: 5
    list: [ "后端开发", "前端技术", "DevOps", "架构设计", "技术杂谈" ]
    colors:  # 分类卡片配色
      - "#2196F3"
      - "#4CAF50"
      - "#FF9800"
      - "#9C27B0"
      - "#E91E63"

rightside:
  readmode: true
  aside: true

datetime_foramt:
  post_card:
    date: YY/MM/DD
    time: HH:mm
  post_info:
    type: updated
    date: MM/DD
    time: HH:mm
  archive:
    date: MM/DD
    time: HH:mm
highlight:
  theme: true
  title: mac
  copy: true
  lang: true
  code_word_wrap: true
  height_limit: 200 # 超出时，显示折叠按钮

  icons:
    # 主题切换图标
    sun: fas fa-sun
    moon: far fa-moon
    # 首页视频播放
    play: fas fa-play
    # 邮箱
    email: far fa-envelope
    # 分类进入图标
    next: fas fa-arrow-right
    # 文章详情 日期
    calendar: far fa-calendar-alt
    # 文章详情 时间
    clock: far fa-clock
    # 文章详情 作者
    user: far fa-user
    # 返回顶部 v1.1.3+
    back_top: fas fa-arrow-up
    # 查询 v1.1.5+
    search: fas fa-search
    # 关闭 v1.1.5+
    close: fas fa-times
    # 打赏 v1.1.7+
    reward: fas fa-hand-holding-usd
    # 用户信息和文章目录切换 v1.2.10+
    user_tag: fas fa-user-alt
    toc_tag: fas fa-th-list
    # 右下角固定按钮 v1.2.11+
    read: fas fa-book-reader
    arrows: fas fa-arrows-alt-h
    # 代码高亮折叠 v2.0.0+
    double_arrows: fas fa-angle-double-down
    # 代码复制
    copy: fas fa-copy

# https://github.com/willin/hexo-wordcount
# Post wordcount | 字数统计
wordcount:
  enable: true # enable | 开启
  count: true # count | 显示字数
  time: true # read time | 显示阅读时间
# Blog search | 搜索
search:
  enable: true
  type: local
# Customize the template path | 自定义模块
layout:
  path: layout # Folder path | 模板存放目录

  # layout
  main: _partial/main # 整体布局结构模板
  header: _partial/header # 顶部菜单栏模板
  banner: _partial/banner # 顶部横幅模板
  sidebar: _partial/sidebar/index # 侧栏模板
  footer: _partial/footer # 页脚模板
  # post
  post_info: _partial/post/post-info # 文章信息模板
  post_content: _partial/post/post-content # 文章内容模板
  reward: _partial/post/reward # 文章信息里打赏模板
  post_copyright: _partial/post/post-copyright # 文章详情版权信息模板
  post_next_prev: _partial/post/post-next-prev # 文章详情上下篇文章模板
  post_card: _partial/post/post-card # 文章卡片信息模板
  post_card_mini: _partial/post/post-card-mini # 文章卡片信息模板
  # widget
  header_logo: _widget/header-logo # 顶部菜单-logo部分
  header_menu: _widget/header-menu # 顶部菜单-菜单部分
  header_theme: _widget/header-theme # 顶部菜单-主题切换部分
  header_search: _widget/header-search # 顶部菜单-查询部分
  categorie: _widget/categorie # 分类卡片模板
  paginator: _widget/paginator # 分页模板
  fixed_btn: _widget/fixed-btn # 固定按钮模板
  post_toc: _widget/post-toc # 文章目录
  about_card: _widget/about-card # 关于页面配置卡片模板
  search: _widget/search # 搜索卡片模板 v2.1.11 +
  sidebar_user: _partial/sidebar/card/user # 侧栏 - 用户头像模板
  sidebar_social: _partial/sidebar/card/social # 侧栏 - 社交图标模块
  sidebar_info: _partial/sidebar/card/info # 侧栏 - 用户信息模块
  sidebar_email: _partial/sidebar/card/email # 侧栏 - 邮件模块
  # third-party
  comment: _third-party/comment/index # 评论插件模板
  analytics: _third-party/web-analytics # 统计模板
  # animation
  page_loading: _partial/preloader/page-preloader # 页面切换动画模板
  mode_change: _partial/preloader/change-mode-preloader # 主题切换动画模板
  # page
  page_about: _partial/page/about # 关于页面模块
  page_archive: _partial/page/archive # 归档页面模块
  page_category: _partial/page/category # 分类页面模块
  page_index: _partial/page/index # 首页页面模块
  page_links: _partial/page/links # 友链页面模块
  page_post: _partial/page/post # 文章详情页面模块
  page_tag: _partial/page/tag # 标签页面模块
  # other
  script: _partial/script # 脚本块 v2.1.11 +
  head: _partial/head # head块 v2.1.11 +

# 404 config | 404 配置
not_found:
  path: / # Return path | 返回路径
  name: not_found.name # Button text 按钮显示文案
  text: not_found.text # Tips | 提示文案

links:
  - name: 浮生记 个人博客
    url: https://blog.tdcqcx.cn
    image: /images/site-avatar.jpg
    desc: 浮生若梦，为欢几何
sw: true